# Generated by Django 5.1.2 on 2024-10-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('sustainability_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hurricane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('current_location', models.CharField(max_length=100)),
                ('forecasted_path', models.JSONField()),
                ('past_path', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('medical', 'Medical Supplies')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('food', 'Food Transport'), ('water', 'Water Transport'), ('medical', 'Medical Transport')], max_length=20)),
                ('current_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('route', models.JSONField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
